name = "mod-server"
main = "src/index.js"
compatibility_date = "2024-12-18"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "shadow-cms-db"
database_id = "7a237072-84d7-4be2-bfe0-4a634969ec16"

# Environment variables
[vars]
USERNAME = "Shadow"

# PASSWORD secret Cloudflare Dashboard me set karna hai
